### PR TITLE
Update to yew 0.19

### LINKED ISSUE #15: How to migrate from yew 0.18 to 0.19
I'm using material-yew with yew 0.18, and i want to move to yew 0.19

which would be the way to migrate with material-yew to yew 0.19?

### PR DESCRIPTION
**Pull request by dcchut**
Notes:

- Running `cargo +nightly fmt` generated a lot of whitespace changes in `html!()` calls, which is unfortunate.
- `Cow<'static, str>` replaced with `Option<AttrValue>` since `IntoPropValue` is not implemented on `Cow` anymore.
- `InputData` was removed from yew. I've made some (presumably quite dodgy) changes to handle this - this is probably worth having a closer look at. 

Resolves #15

### CODE REVIEW

**Comment by hamza1311** [comment]
Thanks for this PR! I don't think this crate was ever going to be updated if not for you doing it.

It would be great if you could also update `mwc`. All you have to do is update the npm package, invoke rollup and accommodate for [breaking changes as described in the changelog](https://github.com/material-components/material-web/releases). That can be a separate PR. I'll go ahead and merge this one.

**Comment by jens1205** [comment]
This PR is not yet available on crates.io? There I can only see 0.1.0

**Comment by hamza1311** [comment]
Yes, it hasn't yet been published. If you want to use it, you need to use a git dependency:
```toml
material-yew = { git = "https://github.com/hamza1311/material-yew/", features = ["full"] }
```

**Comment by jens1205** [comment]
Thanks for the immediate response. yes, git dependency is working (first time I used this, so thanks for the opportunity :-))

Is anything preventing the official publishing of the new version?

**Comment by hamza1311** [comment]
Hi, sorry for the very late response. I've published a new version.

cc @jens1205

**Pull request merged**
